# Generated by Django 5.0.6 on 2024-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0002_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
