# Generated by Django 5.0.6 on 2024-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0003_remove_user_login_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='rsapp/static/images/photo_not_found.jpg', null=True, upload_to='userphotos/%Y-%m-%d/<django.db.models.fields.AutoField>/'),
        ),
    ]
