# Generated by Django 5.0.6 on 2024-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='/images/photo_not_found.jpg', null=True, upload_to='userphotos/%Y-%m-%d/<django.db.models.fields.AutoField>/'),
        ),
    ]
