# Generated by Django 5.0.6 on 2024-05-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0007_alter_tenant_maintenance_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalspace',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_spaces', to='rsapp.tenant'),
        ),
    ]
